FROM golang:1.10-alpine
LABEL maintainer "saboyutaka<yutaka.paradigm.shift@gmail.com>"

ENV APP_PATH=${GOPATH}/src/github.com/saboyutaka/grpc-gw-sample

RUN apk add --no-cache --virtual .dep \
	git openssh-client && \
	go get -u github.com/golang/dep/cmd/dep

WORKDIR ${APP_PATH}

ENTRYPOINT ["dep"]
CMD ["ensure", "-v"]
