version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - 9090:9090
    volumes:
      - .:/go/src/github.com/saboyutaka/grpc-gw-server
    command: ["go", "run", "gwsample/server/main.go"]
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/saboyutaka/grpc-gw-server
    command: ["go", "run", "gwsample/gateway/main.go"]
    depends_on:
      - server
  protoc:
    build:
      context: .
      dockerfile: Dockerfile.protoc
    volumes:
      - .:/app
  dep:
    build:
      context: .
      dockerfile: Dockerfile.dep
    volumes:
      - .:/go/src/github.com/saboyutaka/grpc-gw-server